"""Initial migration.

Revision ID: b2bbb114207e
Revises: 
Create Date: 2023-07-25 14:14:29.848246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2bbb114207e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=200), nullable=True))

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('product_id')
        batch_op.drop_column('id')

    op.create_table('images',
    sa.Column('image', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('image')
    )
    # ### end Alembic commands ###
